### ISSUE TITLE
Meteor 1.5.1 - Error

### ISSUE THREAD

**Issue by MaxShv** [peerlibrary/meteor-subscription-data#5]
Hi Mitar,

We are getting the following error with meteor 1.5.1. Any idea on what is causing it?

 _subscriptionDataSet error { [Error: Match error: Match error: Failed Match.Where validation]
   message: 'Match error: Match error: Failed Match.Where validation',
   path: '',
   sanitizedError: 
    { [Error: Match failed [400]]
      isClientSafe: true,
      error: 400,
      reason: 'Match failed',
      details: undefined,
      message: 'Match failed [400]',
      errorType: 'Meteor.Error' },
 _subscriptionDataSet error { [Error: Match error: Match error: Failed Match.Where validation]
 message: 'Match error: Match error: Failed Match.Where validation',
   path: '',
   sanitizedError: 
    { [Error: Match failed [400]]
      isClientSafe: true,
      error: 400,
      reason: 'Match failed',      details: undefined,
      message: 'Match failed [400]',
      errorType: 'Meteor.Error' },

**Comment by mitar** [comment]
Yes, 1.5.1 introduced some breaking changes so this will have to be resolved first.

**Comment by mitar** [comment]
Fixed. Thanks for reporting. Upgrade to 0.6.0.
