### ISSUE TITLE
Use the subscription to emit events?

### ISSUE THREAD

**Issue by theodorDiaconu** [peerlibrary/meteor-subscription-data#7]
Can this communication channel between client and server at subscription level support event sending only from the server ?

Without storing the data in any place.

```js
// server
Meteor.publish('infinite-scroll', function () {
  this.push(object);
  return this.ready()
});

// client
const subscription = Meteor.subscribe('infinite-scroll');
subscription.listen(function (object) { ... })
```

**Comment by mitar** [comment]
Maybe. But this is not really this package than anymore. This package gives you one reactive document per subscription. Not a stream of them or a collection of them. It is like distributed ReactiveDict.

**Comment by theodorDiaconu** [comment]
Got it.
