### ISSUE TITLE
Is this still maintained?  autorun() isn't on publish anymore...

### ISSUE THREAD

**Issue by skandragon** [peerlibrary/meteor-subscription-data#8]
It appears the `Meteor.publish()` has removed the undocumented `this.autorun()` function.  This is the case for meteor 1.10 at least.

Any workaround?

**Comment by mitar** [comment]
This is maintained. `this,autorun()` was never provided by Meteor, [but is by this package](https://github.com/peerlibrary/meteor-reactive-publish).
